### ISSUE TITLE
Rpenv has no version command or help

### ISSUE THREAD

**Issue by rawsyntax** [rentpath/rpenv#15]
```sh
rpenv --version
```

```sh
rpenv -version
```

Neither print any version information. This needs a basic help message with version info at a minimum

**Comment by colinrymer** [comment]
We should setup `--version` and `-v` that returns:

```
rpenv <version number>
```

**Comment by Teapane** [comment]
Fixed here: https://github.com/rentpath/rpenv/pull/16
```
$ rpenv -v 
2.0.1
$ rpenv --version 
2.0.1
```
