### ISSUE TITLE
needs license

### ISSUE THREAD

**Issue by colinrymer** [rentpath/rpenv#2]

**Comment by lfender6445** [comment]
is this repo public? right now there is some language specific to rentpath, wonder if we should remove https://github.com/rentpath/rpenv/blob/master/rpenv.go#L48 and a few other things, then maybe add MIT license

**Comment by databyte** [comment]
Yeah, it'd be cool if I could use it. :grin:

**Comment by jdacronym** [comment]
If anyone asks, the name of the program is short for "Read and Print ENV".
